feat(ci/cd): update ci/cd

diff --git a/.github/workflows/nuxtjs.yml b/.github/workflows/nuxtjs.yml
--- a/.github/workflows/nuxtjs.yml
+++ b/.github/workflows/nuxtjs.yml
@@ -1,12 +1,18 @@
-# https://github.com/actions/deploy-pages#usage
-name: Deploy to GitHub Pages
+# Sample workflow for building and deploying a Nuxt site to GitHub Pages
+#
+# To get started with Nuxt see: https://nuxtjs.org/docs/get-started/installation
+#
+name: Deploy Nuxt site to Pages
 
 on:
-  workflow_dispatch:
+  # Runs on pushes targeting the default branch
   push:
-    branches:
-      - main
+    branches: ["main"]
 
+  # Allows you to run this workflow manually from the Actions tab
+  workflow_dispatch:
+
+# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
 permissions:
   contents: read
   pages: write
@@ -19,20 +25,55 @@ concurrency:
   cancel-in-progress: false
 
 jobs:
+  # Build job
   build:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
-      - run: corepack enable
-      - uses: actions/setup-node@v3
+      - name: Checkout
+        uses: actions/checkout@v4
+      #      - name: Detect package manager
+      #        id: detect-package-manager
+      #        run: |
+      #          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+      #            echo "manager=yarn" >> $GITHUB_OUTPUT
+      #            echo "command=install" >> $GITHUB_OUTPUT
+      #            exit 0
+      #          elif [ -f "${{ github.workspace }}/package.json" ]; then
+      #            echo "manager=npm" >> $GITHUB_OUTPUT
+      #            echo "command=ci" >> $GITHUB_OUTPUT
+      #            exit 0
+      #          else
+      #            echo "Unable to determine package manager"
+      #            exit 1
+      #          fi
+      - name: Setup Node
+        uses: actions/setup-node@v4
         with:
           node-version: "20.18.0"
-
-      - run: npx nypm install
-      - run: npm run build
+      - name: Setup Pages
+        uses: actions/configure-pages@v5
+        with:
+          # Automatically inject router.base in your Nuxt configuration file and set
+          # target to static (https://nuxtjs.org/docs/configuration-glossary/configuration-target/).
+          #
+          # You may remove this line if you want to manage the configuration yourself.
+          static_site_generator: nuxt
+      - name: Restore cache
+        uses: actions/cache@v4
+        with:
+          path: |
+            dist
+            .nuxt
+          key: ${{ runner.os }}-nuxt-build-${{ hashFiles('dist') }}
+          restore-keys: |
+            ${{ runner.os }}-nuxt-build-
+      - name: Install dependencies
+        run: npx nypm install
+      - run: npm run generate
         env:
           NITRO_PRESET: github_pages
-
+      #      - name: Static HTML export with Nuxt
+      #        run: ${{ steps.detect-package-manager.outputs.manager }} run generate
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
         with:
@@ -40,21 +81,11 @@ jobs:
 
   # Deployment job
   deploy:
-    # Add a dependency to the build job
-    needs: build
-
-    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
-    permissions:
-      pages: write      # to deploy to Pages
-      id-token: write   # to verify the deployment originates from an appropriate source
-
-    # Deploy to the github_pages environment
     environment:
-      name: github_pages
+      name: github-pages
       url: ${{ steps.deployment.outputs.page_url }}
-
-    # Specify runner + deployment step
     runs-on: ubuntu-latest
+    needs: build
     steps:
       - name: Deploy to GitHub Pages
         id: deployment
